id: P3F927747
initial_creation_type: input
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA3JT13346
  instance_id: http://purl.bdrc.io/resource/IE3JT13346
  collection_id: http://purl.bdrc.io/resource/PR0ET001
  language_id: None
  title:
    bo:
    - ཆོས་ཚན་སྣ་ཚོགས།
  alt_title: {}
  author: None
  publisher: DharmaDownload
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    4998669025f44e46951c2b678c258947:
      title: ༄༅།་།འདུལ་བ་མདོ་རྩ་བ་བཞུགས་སོ།་།
      volume_number: 1
      base_file: UT3JT13346_001_0006.txt
      reference: http://purl.bdrc.io/resource/VLC25E4598A896D88E
      image_group: null
      quality: null
  reproductionOf: []
created_at: '2021-12-30T16:36:25.877116'
last_modified_at: '2021-12-30T16:36:25.877123'
